/**
 * GRI Centralized Navigation Engine — Master Configuration
 *
 * Requirements Section 4, 5, 9, 11:
 * - Maps the official GRI institutional hierarchy into clean mobile journeys.
 * - Centralizes every route, icon, category, and parent relationship.
 * - Separates "Discover" (Information) from "Services" (Tasks).
 */

import { NavigationItem } from './navigation.types';

// =============================================================================
// MAIN 5 TOP-LEVEL MOBILE TABS
// =============================================================================
export const TOP_LEVEL_TABS: NavigationItem[] = [
  {
    id: 'tab_home',
    title: 'Home',
    subtitle: 'University Overview & Alerts',
    icon: 'home',
    destinationType: 'TAB',
    route: '/(tabs)/home',
    category: 'SYSTEM',
    order: 1,
    enabled: true,
  },
  {
    id: 'tab_discover',
    title: 'Discover',
    subtitle: 'Institutional Directory & Info',
    icon: 'compass',
    destinationType: 'TAB',
    route: '/(tabs)/discover',
    category: 'ABOUT',
    order: 2,
    enabled: true,
  },
  {
    id: 'tab_services',
    title: 'Services',
    subtitle: 'Task-Based Student & Staff Services',
    icon: 'layers',
    destinationType: 'TAB',
    route: '/(tabs)/services',
    category: 'SERVICES',
    order: 3,
    enabled: true,
  },
  {
    id: 'tab_alerts',
    title: 'Alerts',
    subtitle: 'Official Notification Center',
    icon: 'bell',
    destinationType: 'TAB',
    route: '/(tabs)/alerts',
    category: 'SYSTEM',
    order: 4,
    enabled: true,
  },
  {
    id: 'tab_profile',
    title: 'Profile',
    subtitle: 'Personal Secure Workspace',
    icon: 'user',
    destinationType: 'TAB',
    route: '/(tabs)/profile',
    category: 'SYSTEM',
    order: 5,
    enabled: true,
  },
];

// =============================================================================
// DISCOVER — INSTITUTIONAL DIRECTORY HIERARCHY (Section 4)
// =============================================================================
export const DISCOVER_TREE: NavigationItem[] = [
  {
    id: 'disc_about',
    title: 'About GRI',
    subtitle: 'History, Vision, Mission & Accreditation',
    icon: 'building',
    destinationType: 'CONTENT',
    route: '/content/about/overview',
    category: 'ABOUT',
    order: 1,
    children: [
      { id: 'about_history', title: 'History & Founder', icon: 'history', destinationType: 'CONTENT', route: '/content/about/history', category: 'ABOUT', parentId: 'disc_about', order: 1 },
      { id: 'about_vision', title: 'Vision & Mission', icon: 'target', destinationType: 'CONTENT', route: '/content/about/vision', category: 'ABOUT', parentId: 'disc_about', order: 2 },
      { id: 'about_profile', title: 'Institute Profile', icon: 'file-text', destinationType: 'CONTENT', route: '/content/about/profile', category: 'ABOUT', parentId: 'disc_about', order: 3 },
      { id: 'about_accreditation', title: 'NAAC & NIRF Accreditation', icon: 'award', destinationType: 'CONTENT', route: '/content/about/accreditation', category: 'ABOUT', parentId: 'disc_about', order: 4 },
      { id: 'about_regulations', title: 'Statutory Regulations & MoA', icon: 'shield-check', destinationType: 'CONTENT', route: '/content/about/regulations', category: 'ABOUT', parentId: 'disc_about', order: 5 },
    ],
  },
  {
    id: 'disc_governance',
    title: 'Governance',
    subtitle: 'Board of Management & Councils',
    icon: 'landmark',
    destinationType: 'CONTENT',
    route: '/content/governance/overview',
    category: 'GOVERNANCE',
    order: 2,
    children: [
      { id: 'gov_bom', title: 'Board of Management (BoM)', icon: 'users', destinationType: 'CONTENT', route: '/content/governance/bom', category: 'GOVERNANCE', parentId: 'disc_governance', order: 1 },
      { id: 'gov_academic', title: 'Academic Council', icon: 'book-open', destinationType: 'CONTENT', route: '/content/governance/academic-council', category: 'GOVERNANCE', parentId: 'disc_governance', order: 2 },
      { id: 'gov_finance', title: 'Finance Committee', icon: 'dollar-sign', destinationType: 'CONTENT', route: '/content/governance/finance-committee', category: 'GOVERNANCE', parentId: 'disc_governance', order: 3 },
      { id: 'gov_planning', title: 'Planning & Monitoring Board', icon: 'bar-chart-2', destinationType: 'CONTENT', route: '/content/governance/planning-board', category: 'GOVERNANCE', parentId: 'disc_governance', order: 4 },
    ],
  },
  {
    id: 'disc_admin',
    title: 'Administration',
    subtitle: 'Officers, Deans & Administrative Offices',
    icon: 'user-check',
    destinationType: 'CONTENT',
    route: '/content/administration/overview',
    category: 'ADMINISTRATION',
    order: 3,
    children: [
      { id: 'admin_chancellor', title: 'Chancellor', icon: 'crown', destinationType: 'CONTENT', route: '/content/administration/chancellor', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 1 },
      { id: 'admin_vc', title: 'Vice Chancellor', icon: 'user-check', destinationType: 'CONTENT', route: '/content/administration/vc', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 2 },
      { id: 'admin_registrar', title: 'Registrar', icon: 'clipboard', destinationType: 'CONTENT', route: '/content/administration/registrar', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 3 },
      { id: 'admin_coe', title: 'Controller of Examinations', icon: 'file-text', destinationType: 'CONTENT', route: '/content/administration/coe', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 4 },
      { id: 'admin_fo', title: 'Finance Officer', icon: 'credit-card', destinationType: 'CONTENT', route: '/content/administration/fo', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 5 },
      { id: 'admin_deans', title: 'Deans of Schools', icon: 'graduation-cap', destinationType: 'CONTENT', route: '/content/administration/deans', category: 'ADMINISTRATION', parentId: 'disc_admin', order: 6 },
    ],
  },
  {
    id: 'disc_academics',
    title: 'Academics',
    subtitle: 'Schools, Departments & Programmes',
    icon: 'book-open',
    destinationType: 'CONTENT',
    route: '/content/academics/overview',
    category: 'ACADEMICS',
    order: 4,
    children: [
      { id: 'acad_schools', title: 'Schools & Centres', icon: 'building-2', destinationType: 'CONTENT', route: '/content/academics/schools', category: 'ACADEMICS', parentId: 'disc_academics', order: 1 },
      { id: 'acad_depts', title: 'Academic Departments', icon: 'grid', destinationType: 'CONTENT', route: '/content/academics/departments', category: 'ACADEMICS', parentId: 'disc_academics', order: 2 },
      { id: 'acad_programmes', title: 'Programmes Offered (UG/PG/PhD)', icon: 'list', destinationType: 'CONTENT', route: '/content/academics/programmes', category: 'ACADEMICS', parentId: 'disc_academics', order: 3 },
      { id: 'acad_calendar', title: 'Academic Calendar 2025-26', icon: 'calendar', destinationType: 'CONTENT', route: '/content/academics/calendar', category: 'ACADEMICS', parentId: 'disc_academics', order: 4 },
      { id: 'acad_curriculum', title: 'CBCS Regulations & Syllabi', icon: 'file-text', destinationType: 'CONTENT', route: '/content/academics/curriculum', category: 'ACADEMICS', parentId: 'disc_academics', order: 5 },
    ],
  },
  {
    id: 'disc_admissions',
    title: 'Admissions 2026',
    subtitle: 'Eligibility, Prospectus & Fee Structure',
    icon: 'user-plus',
    destinationType: 'CONTENT',
    route: '/content/admissions/overview',
    category: 'ADMISSIONS',
    order: 5,
    children: [
      { id: 'adm_ug', title: 'Undergraduate (UG) Admissions', icon: 'graduation-cap', destinationType: 'CONTENT', route: '/content/admissions/ug', category: 'ADMISSIONS', parentId: 'disc_admissions', order: 1 },
      { id: 'adm_pg', title: 'Postgraduate (PG) Admissions', icon: 'book-marked', destinationType: 'CONTENT', route: '/content/admissions/pg', category: 'ADMISSIONS', parentId: 'disc_admissions', order: 2 },
      { id: 'adm_phd', title: 'PhD & Research Admissions', icon: 'award', destinationType: 'CONTENT', route: '/content/admissions/phd', category: 'ADMISSIONS', parentId: 'disc_admissions', order: 3 },
      { id: 'adm_fees', title: 'Fee Structure & Prospectus', icon: 'file-text', destinationType: 'CONTENT', route: '/content/admissions/fees', category: 'ADMISSIONS', parentId: 'disc_admissions', order: 4 },
    ],
  },
  {
    id: 'disc_research',
    title: 'Research & RDC',
    subtitle: 'Projects, Publications, Patents & Scholars',
    icon: 'microscope',
    destinationType: 'CONTENT',
    route: '/content/research/overview',
    category: 'RESEARCH',
    order: 6,
    children: [
      { id: 'res_rdc', title: 'Research & Development Cell (RDC)', icon: 'activity', destinationType: 'CONTENT', route: '/content/research/rdc', category: 'RESEARCH', parentId: 'disc_research', order: 1 },
      { id: 'res_projects', title: 'Sponsored Research Projects', icon: 'folder-kanban', destinationType: 'CONTENT', route: '/content/research/projects', category: 'RESEARCH', parentId: 'disc_research', order: 2 },
      { id: 'res_publications', title: 'Publications & Patents', icon: 'file-code', destinationType: 'CONTENT', route: '/content/research/publications', category: 'RESEARCH', parentId: 'disc_research', order: 3 },
    ],
  },
  {
    id: 'disc_campus',
    title: 'Campus & Facilities',
    subtitle: 'Library, Hostels, Health Centre & Labs',
    icon: 'map-pin',
    destinationType: 'CONTENT',
    route: '/content/campus/overview',
    category: 'CAMPUS',
    order: 7,
    children: [
      { id: 'cam_library', title: 'Dr. G. Ramachandran Library', icon: 'library', destinationType: 'CONTENT', route: '/content/campus/library', category: 'CAMPUS', parentId: 'disc_campus', order: 1 },
      { id: 'cam_hostels', title: 'Student Hostels & Mess', icon: 'building', destinationType: 'CONTENT', route: '/content/campus/hostels', category: 'CAMPUS', parentId: 'disc_campus', order: 2 },
      { id: 'cam_health', title: 'Kasturba Hospital & Health Centre', icon: 'heart-pulse', destinationType: 'CONTENT', route: '/content/campus/health', category: 'CAMPUS', parentId: 'disc_campus', order: 3 },
      { id: 'cam_computer', title: 'Computer Centre & Wi-Fi', icon: 'cpu', destinationType: 'CONTENT', route: '/content/campus/computer-centre', category: 'CAMPUS', parentId: 'disc_campus', order: 4 },
    ],
  },
  {
    id: 'disc_placement',
    title: 'Placements',
    subtitle: 'Placement Cell, Drives & Recruiter Info',
    icon: 'briefcase',
    destinationType: 'CONTENT',
    route: '/content/placement/overview',
    category: 'SERVICES',
    order: 8,
  },
  {
    id: 'disc_alumni',
    title: 'Alumni Network',
    subtitle: 'Association, Registration & Events',
    icon: 'users-check',
    destinationType: 'CONTENT',
    route: '/content/alumni/overview',
    category: 'ALUMNI',
    order: 9,
  },
  {
    id: 'disc_enews',
    title: 'E-News & Circulars',
    subtitle: 'News, Tenders, Careers & Archives',
    icon: 'newspaper',
    destinationType: 'CONTENT',
    route: '/content/enews/overview',
    category: 'ENEWS',
    order: 10,
  },
];

// =============================================================================
// TASK-BASED SERVICES (Section 5)
// Distinction: "Services = I want to perform an action"
// =============================================================================
export const SERVICE_ITEMS: NavigationItem[] = [
  {
    id: 'svc_digital_id',
    title: 'Digital Student ID',
    subtitle: 'QR Verified University Student ID Card',
    icon: 'qr-code',
    destinationType: 'ACTION',
    route: '/(tabs)/services?action=digital_id',
    category: 'STUDENT',
    order: 1,
  },
  {
    id: 'svc_samarth_fee',
    title: 'Samarth Fee Portal',
    subtitle: 'Pay Semester & Exam Fees Online',
    icon: 'credit-card',
    destinationType: 'SERVICE',
    route: '/services/fee-payment',
    category: 'SERVICES',
    order: 2,
  },
  {
    id: 'svc_exam_results',
    title: 'Examination & Results',
    subtitle: 'View Grade Sheets, Hall Tickets & Timetables',
    icon: 'file-spreadsheet',
    destinationType: 'SERVICE',
    route: '/services/examinations',
    category: 'EXAMINATIONS',
    order: 3,
  },
  {
    id: 'svc_hostel_pass',
    title: 'Hostel Out-Pass & Leave',
    subtitle: 'Apply for Leave & Out-Pass Requests',
    icon: 'building-2',
    destinationType: 'SERVICE',
    route: '/services/hostel-leave',
    category: 'CAMPUS',
    order: 4,
    allowedRoles: ['student', 'scholar', 'warden', 'admin'],
  },
  {
    id: 'svc_library_opac',
    title: 'Library OPAC Catalog',
    subtitle: 'Search Books, Check Due Dates & Renewals',
    icon: 'library',
    destinationType: 'SERVICE',
    route: '/services/library-catalog',
    category: 'CAMPUS',
    order: 5,
  },
  {
    id: 'svc_grievance',
    title: 'Grievance Portal',
    subtitle: 'Submit & Track Complaints (CRAMS)',
    icon: 'alert-circle',
    destinationType: 'SERVICE',
    route: '/services/grievance-portal',
    category: 'SERVICES',
    order: 6,
  },
  {
    id: 'svc_doc_vault',
    title: 'Document Vault',
    subtitle: 'Download Hall Tickets, Transcripts & Certificates',
    icon: 'download',
    destinationType: 'SERVICE',
    route: '/services/document-vault',
    category: 'SERVICES',
    order: 7,
  },
  {
    id: 'svc_transport',
    title: 'Transport & Bus Pass',
    subtitle: 'Bus Routes, Schedules & Pass Renewal',
    icon: 'bus',
    destinationType: 'SERVICE',
    route: '/services/transport-bus',
    category: 'CAMPUS',
    order: 8,
  },
];
